#!/usr/bin/env python
"""
Trivial voice keyer utility.

Copyright 2014 by Jeffrey M. Laughlin

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""


import serial
import os
import sys

sp = serial.Serial("/dev/ttyUSB0", rtscts=1)

sp.setRTS(1)

# play sound
os.system("aplay " + sys.argv[1])

sp.setRTS(0)

sp.close

